### ISSUE TITLE
We are wondering if the openEuler images can be put online at 'mirrors.sdu.edu.cn'. Thanks

### ISSUE THREAD

**Issue by GeorgeCao-hw** [SDU-Mirrors/issues#3]
Hello, we are the openEuler Community Infrastructure team.
We hope that the **openEuler** OS image file can be put online at the site : ' mirrors.sdu.edu.cn/#/mirror ' 
Here is a brief introduction to the openEuler community and the openEuler operating system:
openEuler is a free open source Linux distribution. openEuler builds an open, diverse and architecturally inclusive software ecosystem with global developers through an open community format, incubates support for multiple processor architectures, covers the full range of digital facilities, and promotes the prosperous development of enterprise digital infrastructure software and hardware, and application ecology.

Website: https://www.openeuler.org/
Email: public@openeuler.sh
Repo address: https://repo.openeuler.org/
our_mirror_list: https://www.openeuler.org/zh/mirror/list/
Space occupied: 2.0T

You can synchronize images as follows:
rsync://121.36.97.194/openeuler/
rsync://root@mirrors.tuna.tsinghua.edu.cn/openeuler
rsync://root@mirror.sjtu.edu.cn/openeuler/

Best regards.

**Comment by SadPencil** [comment]
Considering the disk space, we plan to mirror your content after hardware maintenance, which has been delayed for COVID.

**Comment by GeorgeCao-hw** [comment]
@SadPencil Thank you~

**Comment by SadPencil** [comment]
We apologize for the inconvenience, but at the moment, we regret to inform you that we cannot fulfill your openEuler mirroring request. This is primarily due to our current capacity constraints. Despite successfully migrating servers, the limited funds available have resulted in inadequate disk space to accommodate a repository of 4 TB in size. Our priority is to allocate disk space for more commonly used Linux distributions.
